### ISSUE TITLE
Add Questions to app.js

### ISSUE THREAD

**Issue by sudhajobs0107** [sudhajobs0107/Quiz-Master#1]
We need to add more questions to the Quiz Master application in app.js. The questions should be related to various topics (e.g., programming, history, science).

**Comment by Archanakaushish** [comment]
Hey @sudhajobs0107 , I'm interested in this issue. Can you assign this issue to me?

**Comment by Ankit-Sharma-Dev** [comment]
Hi @sudhajobs0107 , I noticed that @Archanakaushish  has expressed interest in this issue. I would also love to contribute by adding diverse questions to the Quiz Master application. I have some ideas ready and can start working on it immediately. 

If it’s possible, I’d appreciate being assigned this issue as well. If there’s any specific direction or format you prefer for the questions, please let me know!

Thank you!

**Comment by sudhajobs0107** [comment]
Thanks @Ankit-Sharma-Dev !!! Feel free to contribute and let me know if you need any specific guidance. 😊

**Comment by Ankit-Sharma-Dev** [comment]
Thanks for the opportunity, @sudhajobs0107 ! How many questions would you like me to add to the Quiz Master application? I’m ready to get started!

**Comment by sudhajobs0107** [comment]
Hey @harith-hacky03 , Feel free to contribute and let me know if you need any specific guidance. 😊

**Comment by harith-hacky03** [comment]
>  Hey @harith-hacky03 , Feel free to contribute and let me know if you need any specific guidance. 😊

I created my PR , check it out if any changes are needed please let me know.Thank you!

**Comment by ShadowAdi** [comment]
Hey @sudhajobs0107 Can We add Google Gemini Api to generate  Question Based on topics

**Comment by sudhajobs0107** [comment]
Hii @prashantrai-30 , feel free to contribute and let me know if you need any specific guidance. 😊

**Comment by sudhajobs0107** [comment]
Hii @ShadowAdi , Yes you can use the Google Gemini API to generate topic-based questions but don't forget to add hacktoberfest label.

**Comment by prashantrai-30** [comment]
Hey @sudhajobs0107 I have raised  PR regarding this,please review it.
